apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::354704613935:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-IKK4ZFQZC7N3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::354704613935:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-28T12:22:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "788"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cb1e8db1-83c3-425f-966e-b2a883aabf2f
